### ISSUE TITLE
Add section capacity

### ISSUE THREAD

**Issue by msereeyothin** [msereeyothin/ScheduleNu#23]
display the section capacity, and the amount of remaining seats for each section in each section (sectionItem). If the capacity is full, then include an indicator like a exclamation mark to warn users.

to do this, you must change the 'Section' type to accommodate for these values. You also have to change the API query so we can actually fetch these fields.

Check out GraphQL API queries here:
https://studio.apollographql.com/sandbox/explorer

**Comment by msereeyothin** [comment]
I added section capacity in pr #33, so if you merge that then rebase then you shouldn't need to update the api or type

**Comment by xingmeizhi** [comment]
Got it, thanks!
