### ISSUE TITLE
Fix removeSection logic

### ISSUE THREAD

**Issue by xingmeizhi** [msereeyothin/ScheduleNu#28]
Now, if the users select different sections, but if the time is the same, no sections will be displayed. We might need to change removeSection in the usePlans hook to fix it.
![Xnip2024-04-02_09-42-56](https://github.com/msereeyothin/ScheduleNu/assets/92602862/c6fbe0fb-d3f7-46c2-94cd-011661c9d5ca)

**Comment by msereeyothin** [comment]
nice catch

**Comment by xingmeizhi** [comment]
The bug magically disappeared. Closed

**Comment by xingmeizhi** [comment]
Don't think it's the time that causing the bug. Example: Fall 2024 Boston campus, CS3000. If we select section 2 then section 5 or vice versa., which are at the same time, there's no bug. But if we select Section 1 then Section 4 or vice versa., which are also at the same time, no sections will be displayed even if the section is shown as selected. 
![Xnip2024-04-02_12-13-50](https://github.com/msereeyothin/ScheduleNu/assets/92602862/2e83738c-9485-4336-82e0-f0bb49cc3d09)
![Xnip2024-04-02_12-13-59](https://github.com/msereeyothin/ScheduleNu/assets/92602862/9a38389c-52b7-4492-a951-ca8455030d88)

**Comment by msereeyothin** [comment]
yeah I can look into this

**Comment by msereeyothin** [comment]
woah thats really weird it works for some classes and not for others. I agree it probably is related to how we do removeSection. Adding a sectionID might be a way to fix this.
